repos:
- repo: https://github.com/pre-commit/mirrors-yapf.git
  rev: v0.30.0
  hooks:
  - id: yapf
    args: ['--style=.style.yapf', '--parallel', '--in-place']

# - repo: https://github.com/charliermarsh/ruff-pre-commit
#   # Ruff version.
#   rev: 'v0.0.191'
#   hooks:
#     - id: ruff

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  -   id: check-yaml
  -   id: trailing-whitespace
