repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
      args:
        - --allow-multiple-documents
    - id: debug-statements
    - id: detect-private-key
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-yapf.git
  rev: v0.30.0
  hooks:
  - id: yapf
    args: ['--style=.style.yapf', '--parallel', '--in-place']

# - repo: https://github.com/charliermarsh/ruff-pre-commit
#   # Ruff version.
#   rev: 'v0.0.191'
#   hooks:
#     - id: ruff
