repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: pretty-format-json
    - id: check-toml
    - id: check-yaml
      args:
        - --allow-multiple-documents
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-yapf.git
  rev: v0.32.0
  hooks:
  - id: yapf
    args: ['--style=.style.yapf', '--parallel', '--in-place']
    additional_dependencies: [toml]
