org: hasanozdem1r
app: http-api-example
service: lambda_api
provider:
  name: aws
  runtime: python3.9
  stage: ${self:custom.stage}
  region: eu-west-1 # Ireland
  timeout: 15 # The default is 6 seconds.

functions: ${file(handlers/endpoints.yml)}

useDotenv: true

custom:
  stage: ${opt:stage, "dev"}
  pythonRequirements: ${file(resources/python_dependencies.yml)}
  localstack:
    stages:
      - ${self:custom.stage}
    host: http://localhost
    edgePort: 4566
    autostart: true

    docker:
      sudo: false
  DB_NAME: ${env:DB_NAME}
  DB_USER: ${env:DB_USER}
  DB_PASSWORD: ${env:DB_PASSWORD}
  DB_HOST: ${env:DB_HOST}
  DB_PORT: ${env:DB_PORT}


plugins:
  - serverless-python-requirements
  - serverless-localstack
  - serverless-iam-roles-per-function
  - serverless-offline
